[package]
name = "my-project"
version = "0.1.0"
authors = ["runner"]
edition = "2021"
default-run = "binary_search"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
